# Exclude a variety of commonly ignored directories.
exclude = [
    ".git",
    ".idea",
    ".venv",
    ".mysql",
    ".vscode",
    ".vscode",
    ".ruff_cache",
    "manage.py",
    "migrations",
    "__pycahce__",
    "webvirtcloud/settings",
]
line-length = 120
indent-width = 4
target-version = "py310"

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
docstring-code-format = true

[lint]
ignore = ["E501"]
